name: CI

on:
  - push

env:
  BUNDLE_PATH: vendor/bundle

jobs:
  test:
    name: Tests
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.2'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: "Tests and Lint"
        run: bundle exec rake
